const path = require('path');

exports.PERSONALITIES_FOLDER = path.join(process.env.APPDATA, 'EDDI', 'personalities');
exports.PERSONALITY_FILENAME = '_personality.json';

// list of personalities that can't be edited. Only add to this list.
exports.DEFAULT_PERSONALITIES = ['Default unedited'];

exports.GENERATED_MESSAGE = '{_ Generated by eddi-cli _}';
exports.CLI_COMMENT_WHITELIST = ['description', 'priority', 'enabled'];

exports.BUILD_BAT = `npx eddi-cli build
pause`;
exports.WATCH_BAT = `npx eddi-cli watch
pause`;