const path = require('path');

exports.PERSONALITIES_FOLDER = path.join(process.env.APPDATA, 'EDDI', 'personalities');
exports.PERSONALITY_FILENAME = '_personality.json';
exports.CONFIG_FILENAME = '.eddi-cli-config.json';

// list of personalities that can't be edited. Only add to this list.
exports.DEFAULT_PERSONALITIES = ['Default unedited'];

exports.GENERATED_MESSAGE = '{_ Generated by eddi-cli _}';
exports.CLI_COMMENT_SETTINGS = {
  'personality': {
    value: (script, personality) => personality.name,
    readOnly: true,
  },
  'description': {
    readOnly: (script) => script.responder,
  },
  'enabled': {
    include: (script) => script.responder,
    readOnly: (script) => !script.responder,
  },
  'priority': {
    include: (script) => script.responder,
    readOnly: (script) => !script.responder,
  },
}

exports.BATCH_FILES = [
  'build',
  'watch',
  'create',
  'reconcile'
]
