const path = require('path');

exports.PERSONALITIES_FOLDER = path.join(process.env.APPDATA, 'EDDI', 'personalities');
exports.PERSONALITY_FILENAME = '_personality.json';
exports.GENERATED_MESSAGE = '{_ Generated by eddi-cli _}';

exports.BUILD_BAT = `npx eddi-cli build
pause`;
exports.WATCH_BAT = `npx eddi-cli watch
pause`;